name: Project pipeline

on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Backend images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./Backend 
        file: ./Backend/dockerfileBackend  
        run: docker build -t ctbama/backend-app  .
    - name: Publish Image to docker hub
      run: docker push ctbama/backend-app:latest 

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ctbama/backend-app:latest 
      - name: Delete old container
        run: docker rm -f backend-app-container  
      - name: Run Docker Container
        run: docker run -d -p 2000:2000 --name backend-app-container -e DB_URL='${{ secrets.DB_URL }}' ctbama/backend-app
