name: Project pipeline

on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Backend images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./Backend 
        file: ./Backend/dockerfile
        run: docker build -t ctbama/backend-app  .
    - name: Publish Image to docker hub
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./Backend 
        file: ./Backend/dockerfile
        run: docker push ctbama/backend-app:latest
    - name: Build Docker frontend images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./frontend 
        file: ./frontend/dockerfile
        run: docker build -t ctbama/frontend-app  .
    - name: Publish Image to docker hub
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./frontend 
        file: ./frontend/dockerfile
        run: docker push ctbama/frontend-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull backend image from docker hub
        run: docker pull ctbama/backend-app:latest
      - name: Delete old backend container
        run: docker rm -f backend-app-container  
      - name: Run Docker backend Container
        run: docker run -d -p 2000:2000 --name backend-app-container -e DB_URL='${{ secrets.DB_URL }}' ctbama/backend-app
      - name: Pull frontend image from docker hub
        run: docker pull ctbama/frontend-app:latest
      - name: Delete old frontend container
        run: docker rm -f frontend-app-container  
      - name: Run Docker frontend Container
        run: docker run -d -p 3000:80 --name frontend-app-container ctbama/frontend-app
